# Generated by Django 4.1.5 on 2023-02-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_vision', '0002_alter_projectsvision_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesvision',
            name='owner',
            field=models.CharField(default='Лаборатория Техического зрения', max_length=255),
        ),
        migrations.AddField(
            model_name='projectsvision',
            name='owner',
            field=models.CharField(default='Лаборатория Технического зрения', max_length=255),
        ),
        migrations.AddField(
            model_name='technologiesvision',
            name='owner',
            field=models.CharField(default='Лаборатория Технического зрения', max_length=255),
        ),
    ]
