# Generated by Django 4.1.5 on 2023-02-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('durations', models.IntegerField(verbose_name='Продолжительность курса (часы)')),
                ('lector', models.CharField(max_length=255, verbose_name='Имя лектора')),
                ('course_link', models.URLField(verbose_name='Ссылка на курс')),
                ('owner', models.CharField(default='Лаборатория Точного земледелия', max_length=255)),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='ProjectsAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(default='', verbose_name='Описание проекта')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
                ('time_created', models.DateField(verbose_name='Время создания')),
                ('owner', models.CharField(default='Лаборатория Точного земледелия', max_length=255)),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя технологии')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(default='', verbose_name='Описание технологии')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
                ('time_created', models.DateField(verbose_name='Время создания')),
                ('owner', models.CharField(default='Лаборатория Точного земледелия', max_length=255)),
            ],
            options={
                'verbose_name': 'Технологии',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesImgAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.technologiesagriculture', verbose_name='Привязать изображения к')),
            ],
            options={
                'verbose_name': 'Изображения Технологии',
                'verbose_name_plural': 'Изображения Технологии',
            },
        ),
        migrations.CreateModel(
            name='ProjectsImgAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.projectsagriculture', verbose_name='Привязать изображения к')),
            ],
            options={
                'verbose_name': 'Изображения для технологии',
                'verbose_name_plural': 'Изображения для технологии',
            },
        ),
    ]
