# Generated by Django 4.1.5 on 2023-02-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_alter_projectsagriculture_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesagriculture',
            name='owner',
            field=models.CharField(default='Лаборатория Точного земледелия', max_length=255),
        ),
        migrations.AddField(
            model_name='projectsagriculture',
            name='owner',
            field=models.CharField(default='Лаборатория Точного земледелия', max_length=255),
        ),
        migrations.AddField(
            model_name='technologiesagriculture',
            name='owner',
            field=models.CharField(default='Лаборатория Точного земледелия', max_length=255),
        ),
    ]
