# Generated by Django 4.1.7 on 2023-03-25 19:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание проекта')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
                ('time_created', models.DateField(verbose_name='Время создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory', verbose_name='Относится к')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя технологии')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание технологии')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
                ('time_created', models.DateField(verbose_name='Время создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory', verbose_name='Относится к')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.technologies')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('durations', models.IntegerField(verbose_name='Продолжительность курса (часы)')),
                ('lector', models.CharField(max_length=255, verbose_name='Имя лектора')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание курса')),
                ('course_link', models.URLField(verbose_name='Ссылка на курс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory', verbose_name='Относится к')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
