# Generated by Django 4.1.5 on 2023-02-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('durations', models.IntegerField(verbose_name='Продолжительность курса (часы)')),
                ('lector', models.CharField(max_length=255, verbose_name='Имя лектора')),
                ('course_link', models.URLField(verbose_name='Ссылка на курс')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(default='', verbose_name='Описание проекта')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
                ('time_created', models.DateField(verbose_name='Время создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя технологии')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(default='', verbose_name='Описание технологии')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
                ('time_created', models.DateField(verbose_name='Время создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.technologies')),
            ],
        ),
        migrations.DeleteModel(
            name='CoursesRobotics',
        ),
        migrations.RemoveField(
            model_name='technologiesimgrobotics',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ProjectsImgRobotics',
        ),
        migrations.DeleteModel(
            name='ProjectsRobotics',
        ),
        migrations.DeleteModel(
            name='TechnologiesImgRobotics',
        ),
        migrations.DeleteModel(
            name='TechnologiesRobotics',
        ),
        migrations.AddField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory'),
        ),
    ]
