# Generated by Django 4.1.7 on 2023-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='durations',
            field=models.TimeField(verbose_name='Продолжительность курса (часы)'),
        ),
    ]
