# Generated by Django 4.1.5 on 2023-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsrobotics',
            name='time_created',
            field=models.DateField(verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='technologiesrobotics',
            name='time_created',
            field=models.DateField(verbose_name='Время создания'),
        ),
    ]
