# Generated by Django 4.1.5 on 2023-02-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0002_courses_laboratory_projects_projectsimg_technologies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default='', verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory', verbose_name='Относится к'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory', verbose_name='Относится к'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.laboratory', verbose_name='Относится к'),
        ),
    ]
