# Generated by Django 4.1.7 on 2023-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0003_alter_courses_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='technologies',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='courses',
            name='durations',
            field=models.DurationField(verbose_name='Продолжительность курса'),
        ),
    ]
