# Generated by Django 4.1.5 on 2023-02-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('content', models.TextField(default='', verbose_name='Содержание')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('time_created', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateField(auto_now=True, verbose_name='Время обновления')),
                ('video_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопросы студентов')),
                ('content', models.TextField(default='', verbose_name='Ответ на вопрос')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Студентам',
                'verbose_name_plural': 'Студентам',
            },
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.news', verbose_name='Привязать к новости:')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
