# Generated by Django 4.1.5 on 2023-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на видео'),
        ),
    ]
