# Generated by Django 4.1.5 on 2023-02-01 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='news',
            name='time_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 2, 1, 13, 3, 40, 587839, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='time_updated',
            field=models.DateField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок новости'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.news', verbose_name='Привязать к новости:'),
        ),
        migrations.AlterField(
            model_name='newsvideo',
            name='news',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cluster.news', verbose_name='Привязать к новости:'),
        ),
        migrations.AlterField(
            model_name='newsvideo',
            name='video_link',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
    ]
