# Generated by Django 4.1.5 on 2023-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_alter_news_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопросы студентов')),
                ('content', models.TextField(default='', verbose_name='Ответ на вопрос')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Студентам',
                'verbose_name_plural': 'Студентам',
            },
        ),
    ]
